apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - setup.yaml

patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --crd-pattern=resources.azure.com/*;containerservice.azure.com/*;keyvault.azure.com/*;managedidentity.azure.com/*;eventhub.azure.com/*      
    target:
      kind: Deployment