# Mounting the secret only will not work:
#  https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver
#
# "The secrets will sync only after you start a pod to mount them. 
#  To rely solely on syncing with the Kubernetes secrets feature doesn't work. 
#  When all the pods that consume the secret are deleted, the Kubernetes secret is also deleted"
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-secret
spec:
  provider: azure
  secretObjects:
  - data:
    - key: 
      objectName: 
    secretName: 
    type: Opaque
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: 
    keyvaultName: 
    cloudName: ""
    objects: |
      array:
        - |
          objectName: 
          objectType:  
          objectVersion: ""
    tenantId: 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-kv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
        - name: busybox
          image: k8s.gcr.io/e2e-test-images/busybox:1.29-1
          command:
            - "/bin/sleep"
            - "10000"
          volumeMounts:
            - name: secrets-store01
              mountPath: "/mnt/secrets-store"
              readOnly: true
          env:
            - name: NOS-KV-SECRET
              valueFrom:
                secretKeyRef:
                  name: nos-secret-kv
                  key: mynoscs
      volumes:
        - name: secrets-store01
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kv-secret"
                     