apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-volume
spec:
  provider: azure           
  parameters:
    usePodIdentity: "false"               # Set to true for using aad-pod-identity to access your key vault
    keyvaultName: 
    useVMManagedIdentity: "true"
    userAssignedIdentityID: 
    tenantId: 
    objects: |
      array:
        - |
          objectName: 
          objectType:              # object types: secret, key, or cert
          objectVersion: ""
        - |    
          objectName: 
          objectType:              # object types: secret, key, or cert
          objectVersion: ""

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-kv-volume
  labels:
    scope: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:      
      labels:
        app: myapp
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
          - containerPort: 80
            protocol: TCP        
        volumeMounts:
        - name: secrets-kiz-kube-kv
          mountPath: /mnt/kv-secrets
          readOnly: true
      nodeSelector:
        kubernetes.io/os: linux
      volumes:
        - name: secrets-kiz-kube-kv
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: azure-kv-volume
