apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-secret
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "2a4dd3ce-9abf-43ff-816e-eeed0af40720"
    keyvaultName: my-kv-rr
    cloudName: ""
    objects: |
      array:
        - |
          objectName: dbConnection
          objectType: secret 
          objectVersion: ""
    tenantId: "16b3c013-d300-468d-ac64-7eda0820b6d3"