kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: chaos-testing
  name: account-chaos-testing-viewer-ewqpw

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: chaos-testing
  name: role-chaos-testing-viewer-ewqpw
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces"]
  verbs: ["get", "watch", "list"]
- apiGroups:
  - chaos-mesh.org
  resources: [ "*" ]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-chaos-testing-viewer-ewqpw
  namespace: chaos-testing
subjects:
- kind: ServiceAccount
  name: account-chaos-testing-viewer-ewqpw
  namespace: chaos-testing
roleRef:
  kind: Role
  name: role-chaos-testing-viewer-ewqpw
  apiGroup: rbac.authorization.k8s.io
