apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
 name: nginx-scale
spec:
 scaleTargetRef:
   kind: Deployment
   name: main-nginx-ingress-controller
 minReplicaCount: 1
 maxReplicaCount: 10
 cooldownPeriod: 60
 pollingInterval: 1
 triggers:
 - type: prometheus
   metadata:
     serverAddress: http://20.13.85.215:80
     metricName: nginx_connections_active_keda
     query: |
       sum(avg_over_time(nginx_ingress_nginx_connections_active{app_kubernetes_io_instance="main"}[1m]))
     threshold: "20"