{
 "title": "Ingress Scaling",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nginx Replicas",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{deployment=\"main-nginx-ingress-controller\", app_kubernetes_io_name=\"kube-state-metrics\"}) by (deployment)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Keda nginx hpa",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(kube_horizontalpodautoscaler_spec_min_replicas{horizontalpodautoscaler=\"keda-hpa-nginx-scale\",service=\"prometheus-kube-state-metrics\"})",
     "legendFormat": "min replicas"
    },
    {
     "expr": "sum(kube_horizontalpodautoscaler_status_current_replicas{horizontalpodautoscaler=\"keda-hpa-nginx-scale\",service=\"prometheus-kube-state-metrics\"})",
     "legendFormat": "current replicas"
    },
    {
     "expr": "sum(kube_horizontalpodautoscaler_spec_max_replicas{horizontalpodautoscaler=\"keda-hpa-nginx-scale\",service=\"prometheus-kube-state-metrics\"})",
     "legendFormat": "max replicas"
    }
   ]
  },
  {
   "title": "Nginx http Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "nginx_ingress_nginx_http_requests_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nginx",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(nginx_ingress_nginx_connections_active{app_kubernetes_io_instance=\"main\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}